'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'bg' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  bg: {
    // Navigation
    'nav.home': 'Начало',
    'nav.products': 'Продукти',
    'nav.process': 'Процес',
    'nav.distributors': 'Дистрибутори',
    'nav.contact': 'Контакти',
    'nav.orderNow': 'Поръчай сега',
    
    // Hero Section
    'hero.title': 'От градината в бутилката',
    'hero.description': '17+ години отглеждаме качествени плодове и зеленчуци в сърцето на Ловешко. Опитайте нашия 100% натурален ябълков сок.',
    'hero.products_button': 'Разгледай Продуктите',
    'hero.distributors_button': 'Станете Дистрибутор',
    
    // Trust Bar
    'trust.experience': '17+ години опит • Основани 2007',
    'trust.location': 'Александрово, Ловеч • Локално производство',
    'trust.family': 'Семеен бизнес • Честност и качество',
    
    // Experience Section
    'experience.text': 'Занимаваме се със земеделие от 17 години (от 2007).',
    
    // About Us
    'about.title': 'НАШАТА ЗЕМЯ',
    'about.heading': 'Александрово: Перфектното място за плодове',
    'about.description1': 'Разположени в сърцето на Ловешка област, нашите земи се ползват от уникален микроклимат - топли дни, хладни нощи и богата почва, идеална за ябълки, череши и круши.',
    'about.description2': 'Водата, която използваме, идва от естествени подпочвени извори, а всяко дърво получава внимание както в дядовите градини.',
    'about.description3': 'Това не е просто ферма - това е наследство, което пазим и развиваме от 2007 година.',
    'about.visit': 'Посетете ни: Александрово 5572, Ловеч',
    'about.hours': 'Работно време: Всеки ден 8:00-17:00',
    
    // Contact
    'contact.title': 'Свържете се с нас',
    'contact.subtitle': 'Очакваме вашето запитване',
    'contact.address': 'Адрес',
    'contact.address_value': 'с. Александрово 5572<br/>Община Ловеч, България',
    'contact.phone': 'Телефон',
    'contact.phone_value': '+359 878 115 494',
    'contact.hours': 'Пон-Съб: 8:00 - 17:00',
    'contact.email': 'Email',
    'contact.email_info': 'teamkasameri@gmail.com',
    'contact.email_sales': 'teamkasameri@gmail.com',
    
    // Products
    'products.title': 'Нашите продукти',
    'products.subtitle': 'От семето до масата - контролираме всеки етап за да гарантираме качество и вкус.',
    'products.apples': 'Ябълки',
    'products.apples_desc': 'Отглеждаме сортове Златна превъзходна, Флорина, Джонаголд и Мелроуз.',
    'products.apples_season': 'Септември - Ноември',
    'products.cherries': 'Череши',
    'products.cherries_desc': 'Сладки и сочни череши, берени на ръка в пика на зрялост.',
    'products.cherries_season': 'Юни - Юли',
    'products.pears': 'Круши',
    'products.pears_desc': 'Ароматни круши с перфектна текстура и естествена сладост.',
    'products.pears_season': 'Август - Октомври',
    'products.melons': 'Пъпеши',
    'products.melons_desc': 'Сочни пъпеши, отгледани под слънцето на Ловешко.',
    'products.melons_season': 'Юли - Август',
    'products.watermelons': 'Диня',
    'products.watermelons_desc': 'Сочни диньи, отглеждани в нашите екологични ферми',
    'products.tomatoes': 'Домати',
    'products.tomatoes_desc': 'Пресни домати с богат вкус за салати и консерви.',
    'products.tomatoes_season': 'Юни - Септември',
    'products.potatoes': 'Картофи',
    'products.potatoes_desc': 'Качествени картофи, отгледани в плодородна почва.',
    'products.potatoes_season': 'Май - Октомври',
    'products.quinces': 'Дюли',
    'products.quinces_desc': 'Ароматни дюли за сладка, конфитюр и традиционни рецепти.',
    'products.quinces_season': 'Октомври - Ноември',
    'products.juice': '100% Ябълков Сок',
    'products.juice_desc': 'Натурален сок без добавена захар, консерванти или оцветители.',
    'products.juice_season': 'Целогодишно',
    'products.vinegar': 'Оцет - Скоро в продажба!',
    'products.learn_more': 'Научи повече →',
    'products.fruits': 'ПЛОДОВЕ',
    'products.vegetables': 'ЗЕЛЕНЧУЦИ',
    'products.drinks': 'НАПИТКИ',
    'products.recommended': 'ПРЕПОРЪЧАНО',
    
    // Process
    'process.title': 'ОТ ПЛОДА ДО БУТИЛКАТА',
    'process.subtitle': 'Нашият процес',
    'process.description': 'Всяка стъпка е проектирана да запази свежестта, вкуса и хранителните стойности на плодовете.',
    'process.harvest': 'Жътва',
    'process.harvest_desc': 'Ръчно берем плодовете в оптимална зрялост',
    'process.sorting': 'Сортиране',
    'process.sorting_desc': 'Внимателна селекция за качество',
    'process.washing': 'Измиване',
    'process.washing_desc': 'Почистване с природна вода',
    'process.pressing': 'Пресоване',
    'process.pressing_desc': 'Студено пресоване за максимален вкус',
    'process.pasteurization': 'Пастьоризация',
    'process.pasteurization_desc': 'Запазване на свежестта',
    'process.bottling': 'Бутилиране',
    'process.bottling_desc': 'Опаковане и етикетиране',
    
    // Sustainability
    'sustainability.title': 'Устойчивост и отговорност',
    'sustainability.water_title': 'Рециклиране на вода',
    'sustainability.water_desc': 'Използваме затворени системи за измиване, които рециклират до 80% от водата.',
    'sustainability.waste_title': 'Нулеви отпадъци',
    'sustainability.waste_desc': 'Джибрите от пресоване стават компост или храна за животни.',
    'sustainability.employment_title': 'Локална заетост',
    'sustainability.employment_desc': 'Осигуряваме над 30 работни места в региона, подкрепяйки местната общност.',
    
    // Distributors
    'distributors.title': 'ПАРТНЬОРСТВО',
    'distributors.subtitle': 'Станете наш дистрибутор',
    'distributors.description': 'Търсим надеждни партньори, които споделят нашата страст за качество и искат да предложат на своите клиенти истински натурални продукти.',
    'distributors.prices': 'Конкурентни цени',
    'distributors.prices_desc': 'Атрактивни търговски условия и маржове',
    'distributors.delivery': 'Гарантирана доставка',
    'distributors.delivery_desc': 'Редовни доставки и гъвкави количества',
    'distributors.marketing': 'Маркетингова подкрепа',
    'distributors.marketing_desc': 'Материали, обучения и промоционална помощ',
    'distributors.exclusivity': 'Регионална ексклузивност',
    'distributors.exclusivity_desc': 'Възможност за защитена територия',
    'distributors.contact_title': 'Свържете се с нас',
    'distributors.form_title': 'Форма за дистрибутори',
    'distributors.company_name': 'Име на фирма *',
    'distributors.company_placeholder': 'Вашата фирма ООД',
    'distributors.phone': 'Телефон *',
    'distributors.phone_placeholder': '+359 888 123 456',
    'distributors.region': 'Регион на дейност *',
    'distributors.region_placeholder': 'София, Пловдив...',
    'distributors.message': 'Съобщение',
    'distributors.message_placeholder': 'Разкажете ни за вашия бизнес...',
    'distributors.submit': 'Изпрати запитване',
    
    // Gallery
    'gallery.title': 'Нашата история в снимки',
    'gallery.subtitle': 'От полето до вашата маса',
    
    // Testimonials
    'testimonials.title': 'Какво казват нашите партньори',
    'testimonials.maria_name': 'Мария Димитрова',
    'testimonials.maria_company': 'BioMarket Sofia',
    'testimonials.maria_review': 'Работим с Касамери вече 3 години. Качеството е винаги на високо ниво, а сокът им е най-продаваният в магазина ни. Клиентите питат специално за него!',
    'testimonials.petar_name': 'Петър Георгиев',
    'testimonials.petar_company': 'ЕкоПазар ЕООД',
    'testimonials.petar_review': 'Надеждни, коректни и винаги навреме с доставките. Плодовете са свежи, а комуникацията е отлична. Силно препоръчвам за дистрибуция!',
    'testimonials.elena_name': 'Елена Стоянова',
    'testimonials.elena_company': 'Ресторант "Традиция"',
    'testimonials.elena_review': 'Използваме техните домати и ябълки в менюто си. Гостите забелязват разликата във вкуса. Това са истински продукти, отгледани с грижа!',
    
    // Footer
    'footer.tagline': '17+ години традиция в отглеждането на качествени плодове и зеленчуци.',
    'footer.products_title': 'Продукти',
    'footer.apples': 'Ябълки',
    'footer.cherries': 'Череши',
    'footer.juice': 'Ябълков сок',
    'footer.all_products': 'Всички продукти',
    'footer.company_title': 'Компания',
    'footer.about_us': 'За нас',
    'footer.our_process': 'Нашият процес',
    'footer.sustainability': 'Устойчивост',
    'footer.contact': 'Контакти',
    'footer.newsletter_title': 'Бюлетин',
    'footer.newsletter_subtitle': 'Абонирайте се за новини и промоции',
    'footer.email_placeholder': 'Email',
    'footer.copyright': '© 2025 Kasameri EOOD. Всички права запазени.',
    'footer.terms': 'Правила и условия',
    'footer.privacy': 'Поверителност',
    'footer.gdpr': 'GDPR',
    'footer.order': 'Поръчай',
    'footer.built_by': 'Изработено от',
    
    // Contact Form
    'contact.form_title': 'Изпратете ни съобщение',
    'contact.name': 'Име *',
    'contact.name_placeholder': 'Вашето име',
    'contact.email_placeholder': 'vashemail@example.com',
    'contact.phone_placeholder': '+359 878 115 494',
    'contact.message_placeholder': 'Как можем да ви помогнем?',
    'contact.submit': 'Изпрати',
    'contact.working_hours_title': 'Работно време',
    'contact.monday_friday': 'Понеделник - Петък',
    'contact.saturday': 'Събота',
    'contact.sunday': 'Неделя',
    'contact.closed': 'Затворено',
    
    // Banner
    'banner.bulkOrders': 'За по-големи поръчки звъннете на',
    'banner.viberNote': 'ВАЖНО: Добавете ни в контакти преди поръчка',
    
    // How to Order
    'howToOrder.title': 'Как да поръчате',
    'howToOrder.step1': 'Разгледайте продуктите',
    'howToOrder.step1Desc': 'Изберете любимите си плодове и зеленчуци',
    'howToOrder.step2': 'Добавете в количката',
    'howToOrder.step2Desc': 'Посочете количество и детайли',
    'howToOrder.step3': 'Завършете поръчката',
    'howToOrder.step3Desc': 'Попълнете данните и изпратете',
    'howToOrder.step4': 'Потвърждаваме веднага',
    'howToOrder.step4Desc': 'Ще се свържем с вас незабавно за потвърждение',
    
    // Common UI
    'common.learnMore': 'Научи повече',
    'common.buy': 'Купи',
    'common.cancel': 'Отказ',
    'common.addToCart': 'Добави в количката',
    'common.cart': 'Количка',
    'common.checkout': 'Поръчка',
    'common.clearCart': 'Изчисти количката',
    'common.quantity': 'Количество',
    'common.box': 'кутия',
    'common.boxes': 'кутии',
    'common.notes': 'Бележки',
    'common.variety': 'Сорт',
    'common.required': 'Задължително',
    'common.perKg': '/ кг',
    'common.perL': '/ л',
    'common.perPack': '/ кутия (3л)',
    'common.recommended': 'ПРЕПОРЪЧАНО',
    'common.categories.fruits': 'ПЛОДОВЕ',
    'common.categories.vegetables': 'ЗЕЛЕНЧУЦИ',
    'common.categories.drinks': 'НАПИТКИ',
    'common.season': 'Сезон',
    'common.currency': 'лв.',
    'common.minQty': 'Мин. количество',
    'common.step': 'Стъпка',
    'common.maxChars': 'макс. символа',
    'common.addedToCart': 'Добавено в количката',
    'common.total': 'Общо',
    'common.subtotal': 'Междинна сума',
    'common.continueShopping': 'Продължи пазаруването',
    'common.remove': 'Премахни',
    'common.edit': 'Редактирай',
    'common.orderFlow': 'Добави в количката → Поръчка → Изпрати по Viber или Messenger',
    'common.startChat': 'Започни чат с нас',
    
    // Seasons
    'season.sep_nov': 'Септември – Ноември',
    'season.may_jul': 'Май – Юли',
    'season.aug_oct': 'Август – Октомври',
    'season.jul_aug': 'Юли – Август',
    'season.jul_sep': 'Юли – Септември',
    'season.jun_sep': 'Юни – Септември',
    'season.may_oct': 'Май – Октомври',
    'season.sep_mar': 'Септември – Март',
    'season.sep_oct': 'Септември – Октомври',
    'season.oct_nov': 'Октомври – Ноември',
    'season.year_round': 'Целогодишно',
    
    // Product Details
    'product.apples.name': 'Ябълки',
    'product.apples.desc': 'Отглеждаме сортове Златна превъзходна, Флорина, Джонаголд и Мелроуз.',
    'product.cherries.name': 'Череши',
    'product.cherries.desc': 'Сладки и сочни череши хрущялка, брани на ръка в пика на зрялост.',
    'product.pears.name': 'Круши',
    'product.pears.desc': 'Ароматни круши с перфектна текстура и естествена сладост.',
    'product.melons.name': 'Пъпеши',
    'product.melons.desc': 'Сочни пъпеши, отгледани под слънцето на Ловешко.',
    'product.watermelons.name': 'Диня',
    'product.watermelons.desc': 'Сочни диньи, отглеждани в нашите екологични ферми',
    'product.tomatoes.name': 'Домати',
    'product.tomatoes.desc': 'Пресни домати с богат вкус за салати и консерви.',
    'product.potatoes.name': 'Картофи',
    'product.potatoes.desc': 'Качествени картофи, отгледани в плодородна почва.',
    'product.quinces.name': 'Дюли',
    'product.quinces.desc': 'Ароматни дюли за сладка, конфитюр и традиционни рецепти.',
    'product.appleJuice.name': '100% Ябълков Сок',
    'product.appleJuice.desc': 'Натурален ябълков сок – 100% истински, без добавена захар и без консерванти. Пакет от 3 литра.',
    
    // Varieties
    'variety.golden': 'Златна превъзходна',
    'variety.florina': 'Флорина',
    'variety.jonagold': 'Джонаголд',
    'variety.melrose': 'Мелроуз',
    
    // Apple Quality
    'quality.first': '1-во качество',
    'quality.second': '2-ро качество',
    'quality.select': 'Изберете качество',
    
    // Cookie Consent
    'cookie.title': 'Бисквитки и поверителност',
    'cookie.description': 'Използваме бисквитки, за да подобрим вашето преживяване на сайта, да запомним вашите предпочитания и да обработваме вашите поръчки. Кликнете "Приеми всички", за да се съгласите с всички бисквитки, или "Персонализирай", за да изберете.',
    'cookie.acceptAll': 'Приеми всички',
    'cookie.rejectAll': 'Отхвърли всички',
    'cookie.customize': 'Персонализирай',
    'cookie.learnMore': 'Научете повече в нашата',
    'cookie.privacyPolicy': 'Политика за поверителност',
    'cookie.settingsTitle': 'Настройки за бисквитки',
    'cookie.necessary': 'Необходими бисквитки',
    'cookie.necessaryDesc': 'Тези бисквитки са необходими за работата на сайта и не могат да бъдат изключени. Те включват запомняне на вашата кошница и езикови предпочитания.',
    'cookie.functional': 'Функционални бисквитки',
    'cookie.functionalDesc': 'Тези бисквитки ни позволяват да запомним вашите предпочитания и да персонализираме вашето преживяване.',
    'cookie.analytics': 'Аналитични бисквитки',
    'cookie.analyticsDesc': 'Тези бисквитки ни помагат да разберем как използвате сайта, за да го подобрим.',
    'cookie.alwaysActive': 'Винаги активни',
    'cookie.savePreferences': 'Запази предпочитания',
    
    // Badges
    'badges.premium': 'ВИСОКА НАЛИЧНОСТ',
    'badges.core': 'Основен продукт - винаги в наличност',
    'badges.featured': 'ПРЕПОРЪЧАНО',
    'badges.comingSoon': 'Скоро',
    'badges.orderNow': 'Поръчайте сега!',
    'badges.outOfStock': 'ИЗЧЕРПАНА НАЛИЧНОСТ',
    
    // Cart
    'cart.empty': 'Количката е празна',
    'cart.itemCount': 'предмета',
    'cart.lineTotal': 'Общо за ред',
    'cart.validation.varietyRequired': 'Моля изберете сорт',
    'cart.validation.qtyMin': 'Моля въведете валидно количество',
    'cart.validation.qtyMax': 'Максимално количество: 100',
    'cart.validation.notesMax': 'Максимум 140 символа',
    
    // Checkout
    'checkout.title': 'Завърши поръчката',
    'checkout.contact': 'Контакти и доставка',
    'checkout.review': 'Преглед и потвърждение',
    'checkout.fullName': 'Три имена',
    'checkout.phone': 'Телефон',
    'checkout.email': 'Имейл',
    'checkout.deliveryMethod': 'Метод на доставка',
    'checkout.delivery': 'Доставка',
    'checkout.pickup': 'Вземане на място',
    'checkout.street': 'Улица и номер',
    'checkout.city': 'Град',
    'checkout.postcode': 'Пощенски код',
    'checkout.preferredTime': 'Предпочитан час',
    'checkout.date': 'Дата',
    'checkout.slot': 'Часов интервал',
    'checkout.payment': 'Плащане',
    'checkout.cod': 'Наложен платеж',
    'checkout.card': 'Карта (скоро)',
    'checkout.notes': 'Бележки към поръчката',
    'checkout.promo': 'Промо код',
    'checkout.apply': 'Приложи',
    'checkout.remove': 'Премахни',
    'checkout.consent': 'Съгласен съм с Условията и Политиката за поверителност.',
    'checkout.errors.required': 'Задължително поле',
    'checkout.errors.phone': 'Невалиден телефонен номер',
    'checkout.errors.email': 'Невалиден имейл',
    'checkout.errors.postcode': 'Невалиден пощенски код',
    'checkout.errors.minWords': 'Моля въведете пълно име (минимум 2 думи)',
    'checkout.errors.consent': 'Трябва да приемете условията',
    'checkout.summary': 'Обобщение',
    'checkout.items': 'Артикули',
    'checkout.deliveryFee': 'Доставка',
    'checkout.discount': 'Отстъпка',
    'checkout.subtotal': 'Междинна сума',
    'checkout.total': 'Общо',
    'checkout.placeOrder': 'Потвърди поръчката',
    'checkout.back': 'Назад',
    'checkout.cancel': 'Отказ',
    'checkout.successTitle': 'Благодарим!',
    'checkout.successText': 'Вашата поръчка беше приета.',
    'checkout.orderId': 'Номер на поръчка',
    'checkout.newOrder': 'Нова поръчка',
    'checkout.print': 'Печат',
    'checkout.editInCart': 'Редактирай в количката',
    'checkout.freeDelivery': 'Безплатна доставка над 40 лв.',
    'checkout.timeSlots.09-12': '09:00 - 12:00',
    'checkout.timeSlots.12-15': '12:00 - 15:00',
    'checkout.timeSlots.15-18': '15:00 - 18:00',
    'checkout.gdpr': 'Данните се използват само за изпълнение на поръчката.',
    'checkout.econt_cod': 'Наложен платеж с Еконт',
    'checkout.our_transport': 'Доставка с наш транспорт',
    'checkout.extra': 'Вход/Етаж/Ап.',
    'checkout.submit': 'Поръчай',
    'checkout.submitting': 'Изпращане...',
    
    // Viber & Success
    'viber.sendOrder': 'Изпрати по Viber',
    'viber.copyOrder': 'Копирай поръчката',
    'viber.copied': 'Поръчката е копирана!',
    'viber.instruction': 'Ако съобщението не се попълни автоматично, просто го поставете (Paste) в чата.',
    'viber.openingViber': 'Отваряне на Viber...',
    'success.title': 'Благодарим!',
    'success.message': 'Вашата поръчка беше подготвена. Изберете как искате да я изпратите:',
    'success.orderNumber': 'Номер на поръчка',
    'success.sendViber': 'Изпрати по Viber',
    'success.sendMessenger': 'Изпрати по Messenger',
    'success.copyText': 'Копирай текста',
    'success.sendTo': 'Изпратете на:',
    'success.viberNumber': 'Viber: +359878115494',
    'success.messengerProfile': 'Messenger: @BlameH1M',
    
    // Gallery Section
    'gallery.caption.ourGardens': 'Нашите градини',
    'gallery.caption.harvest': 'Жътва',
    'gallery.caption.naturalJuice': 'Натурален сок',
    'gallery.caption.harvestWithCare': 'Жътва с грижа',
    'gallery.caption.packaging': 'Опаковане',
    'gallery.caption.modernTech': 'Модерни технологии',
    'gallery.caption.team': 'Екипът',
    'gallery.caption.product': 'Продукт',
    'gallery.caption.qualityControl': 'Контрол на качеството',
    'gallery.caption.fruits': 'Плодове',
    'gallery.caption.tradition': 'Традиция',
    'gallery.caption.apples': 'Ябълки',
    'gallery.caption.inGarden': 'В градината',
    'gallery.caption.sorting': 'Сортиране',
    'gallery.caption.workWithCare': 'Работа с грижа',
    'gallery.caption.freshHarvest': 'Прясна реколта',
    'gallery.caption.quality': 'Качество',
    'gallery.caption.ourPassion': 'Нашата страст',
    'gallery.caption.fromHeart': 'От сърце',
    
    // Process Steps  
    'process.step1.title': 'Нашите градини',
    'process.step1.desc': 'Всичко започва в нашите екологични градини, където природата и грижата се срещат.',
    'process.step1.details': 'Отглеждаме плодовете си в плодородни почви, богати на минерали и хранителни вещества. Всяко дърво получава индивидуално внимание и грижа през целия сезон.',
    'process.step2.title': 'Ръчно бране',
    'process.step2.desc': 'Всеки плод е внимателно избран на ръка в момента на перфектна зрялост.',
    'process.step2.details': 'Нашият екип от опитни работници познава всяко дърво и бере само най-качествените плодове. Това гарантира, че само най-добрите стигат до вас.',
    'process.step3.title': 'Модерни машини',
    'process.step3.desc': 'Използваме съвременно оборудване за преработка, което запазва качеството.',
    'process.step3.details': 'Най-новите технологии за измиване, сортиране и пресоване осигуряват максимална хигиена и ефективност, като същевременно запазват всички полезни вещества.',
    'process.step4.title': 'Контрол на качеството',
    'process.step4.desc': 'Всяка партида преминава през строг контрол и тестване за качество.',
    'process.step4.details': 'Проверяваме всеки етап от процеса - от pH нивата до бактериологичните тестове. Нищо не минава без нашето одобрение.',
    'process.step5.title': 'Любов към процеса',
    'process.step5.desc': 'В края на краищата, най-важната съставка е любовта към това, което правим.',
    'process.step5.details': 'Всеки член от нашето семейство Касамери влага сърце и душа в производството. Това е нашата страст, не просто работа.',
    'process.sectionTitle': 'ОТ ГРАДИНАТА ДО ВАШАТА МАСА',
    'process.heading': 'Нашият процес на работа',
    'process.intro': 'Всяка стъпка е изпълнена с грижа, внимание и страст към качеството. Така създаваме продукти, на които можете да се доверите.',
    'process.madeWithLove': 'Направено с любов',
    'process.tasteDifference': 'Вкусете разликата',
    'process.careDescription': 'Нашата грижа и внимание към детайлите правят продуктите ни специални. Всяка глътка разказва история за традиция и качество.',
    'process.orderNow': 'Поръчайте сега',
    
    // Forms
    'form.viberRedirect': 'Ще бъдете пренасочени към Viber за изпращане на запитването',
    
    // Badges
    'badges.highAvailability': 'ВИСОКА НАЛИЧНОСТ',
    'badges.recommended': 'ПРЕПОРЪЧАНО',
    'badges.coreProduct': 'Основен продукт - винаги в наличност',
    'badges.learnMore': 'Научи повече',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.process': 'Process',
    'nav.distributors': 'Distributors',
    'nav.contact': 'Contact',
    'nav.orderNow': 'Order Now',
    
    // Hero Section
    'hero.title': 'From Our Orchard to Your Table',
    'hero.description': '17+ years growing quality fruits and vegetables in the heart of Lovech region. Try our 100% natural apple juice.',
    'hero.products_button': 'View Products',
    'hero.distributors_button': 'Become Distributor',
    
    // Trust Bar
    'trust.experience': '17+ years experience • Founded 2007',
    'trust.location': 'Aleksandrovo, Lovech • Local production',
    'trust.family': 'Family business • Honesty and quality',
    
    // Experience Section
    'experience.text': 'We have been engaged in agriculture for 17 years (since 2007).',
    
    // About Us
    'about.title': 'OUR LAND',
    'about.heading': 'Aleksandrovo: The Perfect Place for Fruits',
    'about.description1': 'Located in the heart of Lovech region, our lands benefit from a unique microclimate - warm days, cool nights and rich soil, ideal for apples, cherries and pears.',
    'about.description2': 'The water we use comes from natural underground springs, and every tree receives attention like in grandfather\'s gardens.',
    'about.description3': 'This is not just a farm - this is a heritage that we preserve and develop since 2007.',
    'about.visit': 'Visit us: Aleksandrovo 5572, Lovech',
    'about.hours': 'Working hours: Every day 8:00-17:00',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We look forward to your inquiry',
    'contact.address': 'Address',
    'contact.address_value': 'Aleksandrovo 5572<br/>Lovech Municipality, Bulgaria',
    'contact.phone': 'Phone',
    'contact.phone_value': '+359 878 115 494',
    'contact.hours': 'Mon-Sat: 8:00 - 17:00',
    'contact.email': 'Email',
    'contact.email_info': 'teamkasameri@gmail.com',
    'contact.email_sales': 'teamkasameri@gmail.com',
    
    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'From seed to table - we control every step to guarantee quality and taste.',
    'products.apples': 'Apples',
    'products.apples_desc': 'We grow Golden Delicious, Florina, Jonagold, and Melrose varieties.',
    'products.apples_season': 'September - November',
    'products.cherries': 'Cherries',
    'products.cherries_desc': 'Sweet and juicy cherries, hand-picked at peak ripeness.',
    'products.cherries_season': 'June - July',
    'products.pears': 'Pears',
    'products.pears_desc': 'Aromatic pears with perfect texture and natural sweetness.',
    'products.pears_season': 'August - October',
    'products.melons': 'Melons',
    'products.melons_desc': 'Juicy melons grown under the Lovech sun.',
    'products.melons_season': 'July - August',
    'products.watermelons': 'Watermelons',
    'products.watermelons_desc': 'Juicy watermelons grown in our eco-friendly farms',
    'products.tomatoes': 'Tomatoes',
    'products.tomatoes_desc': 'Fresh tomatoes with rich flavor for salads and preserves.',
    'products.tomatoes_season': 'June - September',
    'products.potatoes': 'Potatoes',
    'products.potatoes_desc': 'Quality potatoes grown in fertile soil.',
    'products.potatoes_season': 'May - October',
    'products.quinces': 'Quinces',
    'products.quinces_desc': 'Aromatic quinces for jam, marmalade and traditional recipes.',
    'products.quinces_season': 'October - November',
    'products.juice': '100% Apple Juice',
    'products.juice_desc': 'Natural juice without added sugar, preservatives or colorants.',
    'products.juice_season': 'Year-round',
    'products.vinegar': 'Vinegar - Coming Soon!',
    'products.learn_more': 'Learn more →',
    'products.fruits': 'FRUITS',
    'products.vegetables': 'VEGETABLES',
    'products.drinks': 'DRINKS',
    'products.recommended': 'RECOMMENDED',
    
    // Process
    'process.title': 'FROM FRUIT TO BOTTLE',
    'process.subtitle': 'Our Process',
    'process.description': 'Every step is designed to preserve the freshness, taste and nutritional values of the fruits.',
    'process.harvest': 'Harvest',
    'process.harvest_desc': 'Hand-picking fruits at optimal ripeness',
    'process.sorting': 'Sorting',
    'process.sorting_desc': 'Careful selection for quality',
    'process.washing': 'Washing',
    'process.washing_desc': 'Cleaning with natural water',
    'process.pressing': 'Pressing',
    'process.pressing_desc': 'Cold pressing for maximum flavor',
    'process.pasteurization': 'Pasteurization',
    'process.pasteurization_desc': 'Preserving freshness',
    'process.bottling': 'Bottling',
    'process.bottling_desc': 'Packaging and labeling',
    
    // Sustainability
    'sustainability.title': 'Sustainability and Responsibility',
    'sustainability.water_title': 'Water Recycling',
    'sustainability.water_desc': 'We use closed washing systems that recycle up to 80% of water.',
    'sustainability.waste_title': 'Zero Waste',
    'sustainability.waste_desc': 'Pressing residues become compost or animal feed.',
    'sustainability.employment_title': 'Local Employment',
    'sustainability.employment_desc': 'We provide over 30 jobs in the region, supporting the local community.',
    
    // Distributors
    'distributors.title': 'PARTNERSHIP',
    'distributors.subtitle': 'Become Our Distributor',
    'distributors.description': 'We are looking for reliable partners who share our passion for quality and want to offer their customers truly natural products.',
    'distributors.prices': 'Competitive Prices',
    'distributors.prices_desc': 'Attractive trade terms and margins',
    'distributors.delivery': 'Guaranteed Delivery',
    'distributors.delivery_desc': 'Regular deliveries and flexible quantities',
    'distributors.marketing': 'Marketing Support',
    'distributors.marketing_desc': 'Materials, training and promotional assistance',
    'distributors.exclusivity': 'Regional Exclusivity',
    'distributors.exclusivity_desc': 'Opportunity for protected territory',
    'distributors.contact_title': 'Contact Us',
    'distributors.form_title': 'Distributor Form',
    'distributors.company_name': 'Company Name *',
    'distributors.company_placeholder': 'Your Company Ltd.',
    'distributors.phone': 'Phone *',
    'distributors.phone_placeholder': '+359 888 123 456',
    'distributors.region': 'Activity Region *',
    'distributors.region_placeholder': 'Sofia, Plovdiv...',
    'distributors.message': 'Message',
    'distributors.message_placeholder': 'Tell us about your business...',
    'distributors.submit': 'Send Inquiry',
    
    // Gallery
    'gallery.title': 'Our Story in Pictures',
    'gallery.subtitle': 'From Field to Your Table',
    
    // Testimonials
    'testimonials.title': 'What Our Partners Say',
    'testimonials.maria_name': 'Maria Dimitrova',
    'testimonials.maria_company': 'BioMarket Sofia',
    'testimonials.maria_review': 'We have been working with Kasameri for 3 years now. The quality is always at a high level, and their juice is the best-selling in our store. Customers specifically ask for it!',
    'testimonials.petar_name': 'Petar Georgiev',
    'testimonials.petar_company': 'EcoMarket Ltd.',
    'testimonials.petar_review': 'Reliable, correct and always on time with deliveries. The fruits are fresh and communication is excellent. I strongly recommend for distribution!',
    'testimonials.elena_name': 'Elena Stoyanova',
    'testimonials.elena_company': 'Tradition Restaurant',
    'testimonials.elena_review': 'We use their tomatoes and apples in our menu. Guests notice the difference in taste. These are real products grown with care!',
    
    // Footer
    'footer.tagline': '17+ years tradition in growing quality fruits and vegetables.',
    'footer.products_title': 'Products',
    'footer.apples': 'Apples',
    'footer.cherries': 'Cherries',
    'footer.juice': 'Apple Juice',
    'footer.all_products': 'All Products',
    'footer.company_title': 'Company',
    'footer.about_us': 'About Us',
    'footer.our_process': 'Our Process',
    'footer.sustainability': 'Sustainability',
    'footer.contact': 'Contact',
    'footer.newsletter_title': 'Newsletter',
    'footer.newsletter_subtitle': 'Subscribe for news and promotions',
    'footer.email_placeholder': 'Email',
    'footer.copyright': '© 2025 Kasameri EOOD. All rights reserved.',
    'footer.terms': 'Terms and Conditions',
    'footer.privacy': 'Privacy',
    'footer.gdpr': 'GDPR',
    'footer.order': 'Order Now',
    'footer.built_by': 'Built by',
    
    // Contact Form
    'contact.form_title': 'Send Us a Message',
    'contact.name': 'Name *',
    'contact.name_placeholder': 'Your name',
    'contact.email_placeholder': 'yourname@example.com',
    'contact.phone_placeholder': '+359 878 115 494',
    'contact.message_placeholder': 'How can we help you?',
    'contact.submit': 'Send',
    'contact.working_hours_title': 'Working Hours',
    'contact.monday_friday': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.closed': 'Closed',
    
    // Banner
    'banner.bulkOrders': 'For bulk orders call',
    'banner.viberNote': 'IMPORTANT: Add us as a contact before ordering',
    
    // How to Order
    'howToOrder.title': 'How to Order',
    'howToOrder.step1': 'Browse Products',
    'howToOrder.step1Desc': 'Choose your favorite fruits and vegetables',
    'howToOrder.step2': 'Add to Cart',
    'howToOrder.step2Desc': 'Specify quantity and details',
    'howToOrder.step3': 'Complete Your Order',
    'howToOrder.step3Desc': 'Fill in your details and submit',
    'howToOrder.step4': 'We Confirm Immediately',
    'howToOrder.step4Desc': 'We will contact you immediately for confirmation',
    
    // Common UI
    'common.learnMore': 'Learn more',
    'common.buy': 'Buy',
    'common.cancel': 'Cancel',
    'common.addToCart': 'Add to cart',
    'common.cart': 'Cart',
    'common.checkout': 'Checkout',
    'common.clearCart': 'Clear cart',
    'common.quantity': 'Quantity',
    'common.box': 'box',
    'common.boxes': 'boxes',
    'common.notes': 'Notes',
    'common.variety': 'Variety',
    'common.required': 'Required',
    'common.perKg': '/ kg',
    'common.perL': '/ L',
    'common.perPack': '/ box (3L)',
    'common.recommended': 'RECOMMENDED',
    'common.categories.fruits': 'FRUITS',
    'common.categories.vegetables': 'VEGETABLES',
    'common.categories.drinks': 'DRINKS',
    'common.season': 'Season',
    'common.currency': 'лв.',
    'common.minQty': 'Min. quantity',
    'common.step': 'Step',
    'common.maxChars': 'max chars',
    'common.addedToCart': 'Added to cart',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.continueShopping': 'Continue shopping',
    'common.remove': 'Remove',
    'common.edit': 'Edit',
    'common.orderFlow': 'Add to cart → Checkout → Send via Viber or Messenger',
    'common.startChat': 'Start chat with us',
    
    // Seasons
    'season.sep_nov': 'September – November',
    'season.may_jul': 'May – July',
    'season.aug_oct': 'August – October',
    'season.jul_aug': 'July – August',
    'season.jul_sep': 'July – September',
    'season.jun_sep': 'June – September',
    'season.may_oct': 'May – October',
    'season.sep_mar': 'September – March',
    'season.sep_oct': 'September – October',
    'season.oct_nov': 'October – November',
    'season.year_round': 'Year-round',
    
    // Product Details
    'product.apples.name': 'Apples',
    'product.apples.desc': 'We grow Golden Delicious, Florina, Jonagold, and Melrose varieties.',
    'product.cherries.name': 'Cherries',
    'product.cherries.desc': 'Sweet and juicy crunchy cherries, hand-picked at peak ripeness.',
    'product.pears.name': 'Pears',
    'product.pears.desc': 'Aromatic pears with perfect texture and natural sweetness.',
    'product.melons.name': 'Melons',
    'product.melons.desc': 'Juicy melons grown under the Lovech sun.',
    'product.watermelons.name': 'Watermelons',
    'product.watermelons.desc': 'Juicy watermelons grown in our eco-friendly farms',
    'product.tomatoes.name': 'Tomatoes',
    'product.tomatoes.desc': 'Fresh tomatoes with rich flavor for salads and preserves.',
    'product.potatoes.name': 'Potatoes',
    'product.potatoes.desc': 'Quality potatoes grown in fertile soil.',
    'product.quinces.name': 'Quinces',
    'product.quinces.desc': 'Aromatic quinces for jam, marmalade and traditional recipes.',
    'product.appleJuice.name': '100% Apple Juice',
    'product.appleJuice.desc': 'Natural apple juice – 100% authentic, without added sugar and without preservatives. 3-liter pack.',
    
    // Varieties
    'variety.golden': 'Golden Delicious',
    'variety.florina': 'Florina',
    'variety.jonagold': 'Jonagold',
    'variety.melrose': 'Melrose',
    
    // Apple Quality
    'quality.first': '1st Quality',
    'quality.second': '2nd Quality',
    'quality.select': 'Select Quality',
    
    // Cookie Consent
    'cookie.title': 'Cookies and Privacy',
    'cookie.description': 'We use cookies to improve your experience on our site, remember your preferences, and process your orders. Click "Accept All" to consent to all cookies, or "Customize" to choose.',
    'cookie.acceptAll': 'Accept All',
    'cookie.rejectAll': 'Reject All',
    'cookie.customize': 'Customize',
    'cookie.learnMore': 'Learn more in our',
    'cookie.privacyPolicy': 'Privacy Policy',
    'cookie.settingsTitle': 'Cookie Settings',
    'cookie.necessary': 'Necessary Cookies',
    'cookie.necessaryDesc': 'These cookies are essential for the website to function and cannot be disabled. They include remembering your cart and language preferences.',
    'cookie.functional': 'Functional Cookies',
    'cookie.functionalDesc': 'These cookies allow us to remember your preferences and personalize your experience.',
    'cookie.analytics': 'Analytics Cookies',
    'cookie.analyticsDesc': 'These cookies help us understand how you use the site so we can improve it.',
    'cookie.alwaysActive': 'Always Active',
    'cookie.savePreferences': 'Save Preferences',
    
    // Badges
    'badges.premium': 'HIGH AVAILABILITY',
    'badges.core': 'Core product - always in stock',
    'badges.featured': 'RECOMMENDED',
    'badges.comingSoon': 'Coming soon',
    'badges.orderNow': 'Order now!',
    'badges.outOfStock': 'OUT OF STOCK',
    
    // Cart
    'cart.empty': 'Your cart is empty',
    'cart.itemCount': 'items',
    'cart.lineTotal': 'Line total',
    'cart.validation.varietyRequired': 'Please select a variety',
    'cart.validation.qtyMin': 'Please enter a valid quantity',
    'cart.validation.qtyMax': 'Maximum quantity: 100',
    'cart.validation.notesMax': 'Maximum 140 characters',
    
    // Checkout
    'checkout.title': 'Complete your order',
    'checkout.contact': 'Contact & Delivery',
    'checkout.review': 'Review & Confirm',
    'checkout.fullName': 'Full name',
    'checkout.phone': 'Phone',
    'checkout.email': 'Email',
    'checkout.deliveryMethod': 'Delivery method',
    'checkout.delivery': 'Delivery',
    'checkout.pickup': 'Pickup',
    'checkout.street': 'Street & number',
    'checkout.city': 'City',
    'checkout.postcode': 'Postcode',
    'checkout.preferredTime': 'Preferred time',
    'checkout.date': 'Date',
    'checkout.slot': 'Time slot',
    'checkout.payment': 'Payment',
    'checkout.cod': 'Cash on delivery',
    'checkout.card': 'Card (soon)',
    'checkout.notes': 'Order notes',
    'checkout.promo': 'Promo code',
    'checkout.apply': 'Apply',
    'checkout.remove': 'Remove',
    'checkout.consent': 'I agree to the Terms and Privacy Policy.',
    'checkout.errors.required': 'Required field',
    'checkout.errors.phone': 'Invalid phone number',
    'checkout.errors.email': 'Invalid email',
    'checkout.errors.postcode': 'Invalid postcode',
    'checkout.errors.minWords': 'Please enter full name (minimum 2 words)',
    'checkout.errors.consent': 'You must accept the terms',
    'checkout.summary': 'Summary',
    'checkout.items': 'Items',
    'checkout.deliveryFee': 'Delivery',
    'checkout.discount': 'Discount',
    'checkout.subtotal': 'Subtotal',
    'checkout.total': 'Total',
    'checkout.placeOrder': 'Place order',
    'checkout.back': 'Back',
    'checkout.cancel': 'Cancel',
    'checkout.successTitle': 'Thank you!',
    'checkout.successText': 'Your order has been received.',
    'checkout.orderId': 'Order ID',
    'checkout.newOrder': 'New order',
    'checkout.print': 'Print',
    'checkout.editInCart': 'Edit in cart',
    'checkout.freeDelivery': 'Free delivery over 40 лв.',
    'checkout.timeSlots.09-12': '09:00 - 12:00',
    'checkout.timeSlots.12-15': '12:00 - 15:00',
    'checkout.timeSlots.15-18': '15:00 - 18:00',
    'checkout.gdpr': 'Data is used solely for order fulfillment.',
    'checkout.econt_cod': 'Econt cash on delivery',
    'checkout.our_transport': 'Delivery with our transport',
    'checkout.extra': 'Entrance/Floor/Apt',
    'checkout.submit': 'Place Order',
    'checkout.submitting': 'Submitting...',
    
    // Viber & Success
    'viber.sendOrder': 'Send via Viber',
    'viber.copyOrder': 'Copy order',
    'viber.copied': 'Order copied!',
    'viber.instruction': 'If the message is not pre-filled automatically, simply paste it in the chat.',
    'viber.openingViber': 'Opening Viber...',
    'success.title': 'Thank you!',
    'success.message': 'Your order is ready. Choose how you want to send it:',
    'success.orderNumber': 'Order number',
    'success.sendViber': 'Send via Viber',
    'success.sendMessenger': 'Send via Messenger',
    'success.copyText': 'Copy text',
    'success.sendTo': 'Send to:',
    'success.viberNumber': 'Viber: +359878115494',
    'success.messengerProfile': 'Messenger: @BlameH1M',
    
    // Gallery Section
    'gallery.caption.ourGardens': 'Our Gardens',
    'gallery.caption.harvest': 'Harvest',
    'gallery.caption.naturalJuice': 'Natural Juice',
    'gallery.caption.harvestWithCare': 'Harvesting with Care',
    'gallery.caption.packaging': 'Packaging',
    'gallery.caption.modernTech': 'Modern Technology',
    'gallery.caption.team': 'The Team',
    'gallery.caption.product': 'Product',
    'gallery.caption.qualityControl': 'Quality Control',
    'gallery.caption.fruits': 'Fruits',
    'gallery.caption.tradition': 'Tradition',
    'gallery.caption.apples': 'Apples',
    'gallery.caption.inGarden': 'In the Garden',
    'gallery.caption.sorting': 'Sorting',
    'gallery.caption.workWithCare': 'Working with Care',
    'gallery.caption.freshHarvest': 'Fresh Harvest',
    'gallery.caption.quality': 'Quality',
    'gallery.caption.ourPassion': 'Our Passion',
    'gallery.caption.fromHeart': 'From the Heart',
    
    // Process Steps
    'process.step1.title': 'Our Orchards',
    'process.step1.desc': 'Everything starts in our organic orchards, where nature and care meet.',
    'process.step1.details': 'We grow our fruits in fertile soils rich in minerals and nutrients. Every tree receives individual attention and care throughout the season.',
    'process.step2.title': 'Hand Picking',
    'process.step2.desc': 'Every fruit is carefully hand-picked at the moment of perfect ripeness.',
    'process.step2.details': 'Our team of experienced workers knows every tree and picks only the highest quality fruits. This ensures that only the best reach you.',
    'process.step3.title': 'Modern Machinery',
    'process.step3.desc': 'We use modern equipment for processing that preserves quality.',
    'process.step3.details': 'The latest technologies for washing, sorting and pressing ensure maximum hygiene and efficiency while preserving all beneficial substances.',
    'process.step4.title': 'Quality Control',
    'process.step4.desc': 'Every batch goes through strict quality control and testing.',
    'process.step4.details': 'We check every stage of the process - from pH levels to bacteriological tests. Nothing passes without our approval.',
    'process.step5.title': 'Love for the Process',
    'process.step5.desc': 'In the end, the most important ingredient is the love for what we do.',
    'process.step5.details': 'Every member of our Kasameri family puts heart and soul into production. This is our passion, not just work.',
    'process.sectionTitle': 'FROM ORCHARD TO YOUR TABLE',
    'process.heading': 'Our Work Process',
    'process.intro': 'Every step is filled with care, attention and passion for quality. This is how we create products you can trust.',
    'process.madeWithLove': 'Made with Love',
    'process.tasteDifference': 'Taste the Difference',
    'process.careDescription': 'Our care and attention to detail make our products special. Every sip tells a story of tradition and quality.',
    'process.orderNow': 'Order Now',
    
    // Forms
    'form.viberRedirect': 'You will be redirected to Viber to send the inquiry',
    
    // Badges
    'badges.highAvailability': 'HIGH AVAILABILITY',
    'badges.recommended': 'RECOMMENDED',
    'badges.coreProduct': 'Core product - always in stock',
    'badges.learnMore': 'Learn more',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('bg');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'bg' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
